Pod::Spec.new do |s|
  s.name         = "KaguraObfuscator"
  s.version      = "0.2.1"
  s.summary      = "LLVM-based binary obfuscation and runtime protection for iOS/macOS."
  s.description  = <<-DESC
    KaguraObfuscator is a production-grade LLVM pass plugin that provides:
      - Control flow obfuscation (FLA, BCF, BBR, BBS, IBR, DCI, FSplit)
      - Data encryption (STR, STR-AES, WSTR, CO, GENC, PE)
      - Anti-analysis (AntiDebug, AntiTamper, ObjC, SymbolVisibility)
      - Anti-cheat (MVO, Honey, Telemetry, BBCheck)
      - Platform integrations (Xcode build phase, JSON config)
  DESC
  s.homepage     = "https://github.com/ykus4/kagura"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author       = { "kagura" => "kagura@example.com" }
  s.ios.deployment_target = "13.0"
  s.osx.deployment_target = "11.0"

  s.source       = { :git => "https://github.com/ykus4/kagura.git",
                     :tag => "v#{s.version}" }

  # Runtime library sources (compiled into the target app).
  #
  # Exclusions are DIRECTORY-level on purpose: runtime/ is reorganised from
  # time to time, and the previous per-file exclude list silently stopped
  # matching when the flat layout became runtime/{core,anti_debug,ios,android,
  # windows,game}/ — which pulled every Android and Windows source into the
  # iOS pod.
  # VMOpcodes.def is the VM opcode table runtime/core/vm_interpreter.c shares
  # with the pass; without it that file does not compile.
  s.source_files = "runtime/**/*.{c,h}", "include/kagura/game_protect.h",
                   "include/kagura/VMOpcodes.def"
  s.exclude_files = [
    "runtime/android/**/*",  # Bionic / Linux: JNI, SafetyNet, seccomp, APK
    "runtime/windows/**/*",  # Win32: ETW, PE integrity, Windows anti-debug
  ]

  # Only the C++ value-protection template is a consumer-facing header.
  # include/kagura/{Options,Passes,Utils,VM}.h are LLVM pass-plugin headers
  # and must not be published in the pod's public header map.
  s.public_header_files = "include/kagura/game_protect.h"

  # Compiler settings
  s.compiler_flags = "-std=c11"
  s.pod_target_xcconfig = {
    "HEADER_SEARCH_PATHS" => "$(PODS_TARGET_SRCROOT)/include",
    "GCC_OPTIMIZATION_LEVEL" => "2",
  }

  # Xcode build phase script (injects the kagura clang plugin)
  # Usage: pod 'KaguraObfuscator'; then run `pod install` and the
  # build phase below is automatically added to your target.
  s.script_phases = [
    {
      :name            => "KaguraObfuscator",
      :script          => <<-SCRIPT,
#!/bin/bash
# Auto-generated by KaguraObfuscator CocoaPods integration.
#
# The CMake target is built with no "lib" prefix, so the artifact is
# build/lib/Transforms/KaguraObfuscator.dylib — see the release workflow
# (.github/workflows/release.yml) which copies exactly that path.
KAGURA_ROOT="${KAGURA_ROOT:-${PODS_ROOT}/KaguraObfuscator}"
KAGURA_PLUGIN="${KAGURA_PLUGIN_PATH:-}"

if [ -z "$KAGURA_PLUGIN" ] || [ ! -f "$KAGURA_PLUGIN" ]; then
  for candidate in \
    "${KAGURA_ROOT}/build/lib/Transforms/KaguraObfuscator.dylib" \
    "${KAGURA_ROOT}/build/lib/Transforms/KaguraObfuscator.so"
  do
    if [ -f "$candidate" ]; then KAGURA_PLUGIN="$candidate"; break; fi
  done
fi

KAGURA_PROFILE_JSON="${KAGURA_PROFILE_JSON:-${KAGURA_ROOT}/integration/profiles/balanced.json}"

if [ -n "$KAGURA_PLUGIN" ] && [ -f "$KAGURA_PLUGIN" ]; then
  # Inject via OTHER_CFLAGS — CocoaPods passes these to every source file.
  echo "KaguraObfuscator: plugin loaded from $KAGURA_PLUGIN"
  if [ -f "$KAGURA_PROFILE_JSON" ]; then
    echo "KaguraObfuscator: profile $KAGURA_PROFILE_JSON"
  fi
else
  echo "warning: KaguraObfuscator plugin not found under ${KAGURA_ROOT}/build/lib/Transforms"
  echo "warning: Run 'cmake --build build' in the pod directory first,"
  echo "warning: or set KAGURA_PLUGIN_PATH to an absolute plugin path."
fi
SCRIPT
      :execution_position => :before_compile,
      :show_env_vars_in_log => false,
    }
  ]
end
